apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup-retry
  namespace: rmf-docker-test
spec:
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: keycloak-setup-sa
      restartPolicy: Never
      containers:
        - name: keycloak-setup
          image: ghcr.io/open-rmf/rmf_deployment_template/rmf-deployment/keycloak-setup:latest
          imagePullPolicy: IfNotPresent
          command: ["/keycloak-setup.bash", "https://rmf.test"]

