apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-default-zot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/openkubes/ok-local.git
    targetRevision: main
    path: ok-artifact-registry
  destination:
    name: ok-infra-local
    namespace: ok-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
